Questions:-  https://www.hackerrank.com/domains/python?filters%5Bsubdomains%5D%5B%5D=numpy

**Q1. Arrays**

In [19]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    arr = numpy.array(arr, float)
    return arr[::-1]

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


**Q2 . Shape and Reshape**

In [17]:
import numpy

lst = input().split()

arr = numpy.array(lst, int)

print(numpy.reshape(arr, (3,3)))


1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Q3. Transpose and Flatten**

In [16]:
import numpy

lst = list(map(int, input().split()))
N = lst[0]
M = lst[1]

arr = []
for i in range(N):
    row = list(map(int, input().split()))
    arr.append(row)

arr = numpy.array(arr)    
print(numpy.transpose(arr))
print(arr.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


**Q4. Concatenate**

In [6]:
import numpy

lst = list(map(int, input().split()))
N = lst[0]
M = lst[1]
P = lst[2]

arr_1 = []
arr_2 = []
for i in range(N):
    ele = list(map(int, input().split()))[:P]
    arr_1.append(ele)
    
for i in range(M):
    ele = list(map(int, input().split()))[:P]
    arr_2.append(ele)

arr_1 = numpy.array(arr_1)
arr_2 = numpy.array(arr_2)

array = numpy.concatenate((arr_1, arr_2), axis = 0)

print(array)

4 3 2
1 2
1 2 
1 2
1 2 
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


**Q5. Zeros and Ones**

In [8]:
import numpy
shape = tuple(map(int, input().split()))
print(numpy.zeros(shape, dtype = int))
print(numpy.ones(shape, dtype = int))


3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


**Q6. Eye and Identity**

In [9]:
import numpy

numpy.set_printoptions(legacy = '1.13')

lst = list(map(int, input().split()))
N = lst[0]
M = lst[1]

print(numpy.eye(N,M,k  = 0))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


**Q7. Array Mathematics**

In [13]:
import numpy
lst = list(map(int, input().split()))
n = lst[0]
m = lst[1]
arr_A = []
arr_B = []
for _ in range(n):
    ele = list(map(int, input().split()))[:m]
    arr_A.append(ele)
    
for _ in range(n):
    ele = list(map(int, input().split()))[:m]
    arr_B.append(ele)

arr_A = numpy.array(arr_A)
arr_B = numpy.array(arr_B)

print(arr_A + arr_B)
print(arr_A - arr_B)
print(arr_A * arr_B)
print(arr_A // arr_B)
print(arr_A % arr_B)
print(arr_A ** arr_B)

1 4 
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


**Q8. Floor, Ceil and Rint**

In [15]:
import numpy
numpy.set_printoptions(legacy = '1.13')

a = list(map(float, input().split()))
a = numpy.array(a)

print(numpy.floor(a))
print(numpy.ceil(a))
print(numpy.rint(a))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


**Q9. Sum and Prod**

In [3]:
import numpy

lst = list(map(int, input().split()))
n = lst[0]
m = lst[1]

arr = []
for _ in range(n):
    ele = list(map(int, input().split()))[:m]
    arr.append(ele)

arr = numpy.array(arr)

s = numpy.sum(arr, axis = 0)
print(numpy.prod(arr))

2 2
1 2
3 4
24


**Q10. Min and Max**

In [5]:
import numpy

lst = list(map(int, input().split()))
n = lst[0]
m = lst[1]

arr = []
for _ in range(n):
    s = list(map(int, input().split()))[:m]
    arr.append(s)
    
arr = numpy.array(arr)

mini = numpy.min(arr, axis = 1)
print(numpy.max(mini))

4 2
2 5
3 7
1 3
4 0
3


**Q11. Mean, Var, and Std**

In [8]:
import numpy

lst = list(map(int, input().split()))

n = lst[0]
m = lst[1]

arr = []
for _ in range(n):
    row = list(map(int, input().split()))[:m]
    arr.append(row)
    
arr = numpy.array(arr)

print(numpy.mean(arr, axis = 1))
print(numpy.var(arr, axis = 0))
print(numpy.round(numpy.std(arr, axis = None), 11))

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.11803398875


**Q12. Dot and Cross**

In [9]:
import numpy

n = int(input())

arr_A = []
arr_B = []
for _ in range(n):
    s = list(map(int, input().split()))[:n]
    arr_A.append(s)
    
for _ in range(n):
    s = list(map(int, input().split()))[:n]
    arr_B.append(s)
    

print(numpy.dot(arr_A, arr_B))


2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


**Q13. Inner and Outer**

In [10]:
import numpy

a = list(map(int, input().split()))
b = list(map(int, input().split()))

a = numpy.array(a)
b = numpy.array(b)

print(numpy.inner(a,b))
print(numpy.outer(a,b))



0 1
2 3
3
[[0 0]
 [2 3]]


**Q14. Polynomials**

In [12]:
import numpy

lst = list(map(float, input().split()))
a = int(input())
arr = numpy.array(lst)

print(numpy.polyval(arr, a))

1.1 2 3
0
3.0


**Q15. Linear Algebra**

In [1]:
import numpy

n = int(input())
a = []
for _ in range(n):
    ele = list(map(float, input().split()))[:n]
    a.append(ele)
    
a = numpy.array(a)
print(numpy.round(numpy.linalg.det(a), 2))

2
1.1 1.1
1.1 1.1
0.0
